---
version: "3.7"
networks:
  # docker network create --gateway 192.168.99.1 --subnet 192.168.99.0/24 traefik_proxy
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
  socket_proxy:
    external:
      name: socket_proxy
services:
  traefik:
    image: traefik:v2.3.2
    container_name: traefik
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --entrypoints.http.address=:80
      - --entrypoints.traefik.address=:8080
      - --api=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.network=traefik_proxy
      - --providers.docker.swarmMode=false
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
    networks:
      traefik_proxy:
        ipv4_address: 192.168.99.254
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    networks:
      traefik_proxy:
        ipv4_address: 192.168.99.90
    ports:
      - 9091:9091
    env_file: .env
    environment:
      - CREATE_TUN_DEVICE=true
      - LOCAL_NETWORK=192.168.0.0/16
    volumes:
      - ./transmission/config:/config
      - ./transmission/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=PathPrefix(`/transmission`)"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      traefik_proxy:
        ipv4_address: 192.168.99.89
    ports:
      - 8990:8989
    volumes:
      - ./sonarr:/config
      - ./downloads/tv:/tv
      - ./transmission/data/watch:/downloads
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.sonarr.rule=Host(`sonarr.localhost`)"
      # - "traefik.http.middlewares.sonarr-stripprefix.stripprefix.prefixes=/sonarr"
      - "traefik.http.routers.sonarr.rule=PathPrefix(`/sonarr`)"
      # - "traefik.http.routers.sonarr.middlewares=sonarr-stripprefix@docker"
  whoami:
    image: traefik/whoami
    networks:
      traefik_proxy:
        ipv4_address: 192.168.99.99
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.middlewares=whoami-stripprefix@docker"
      - "traefik.http.middlewares.whoami-stripprefix.stripprefix.prefixes=/whoami"
